### ISSUE TITLE
Enhancement Request - Add an Exclude Parameter

### ISSUE THREAD

**Issue by wwc-trevor** [rhymeswithmogul/PSPasswordGenerator#4]
When making passwords with the command, some systems specify certain characters cannot be used. I ran into this issue when using the command to make a password for my hypervisor.

I am imaging a list of symbols in an exclude switch/parameter.

`Get-RandomPassword -length 20 -exclude %[$`

**Comment by rhymeswithmogul** [comment]
Great idea!

**Comment by rhymeswithmogul** [comment]
I had the day off today, so pull the `exclude-characters` branch and let me know what you think.

**Comment by wwc-trevor** [comment]
I did some testing. The only issues I found with it is `(` or `{` tries to force a new line if not wrapped in quotes `""`.  Then after that, the only symbol giving troubles is the Escape/grave accent ``` ` ```. Since this is the escape symbol. See screenshot of testing:
<details>
  <summary>Screenshot</summary>

![exclude-characters-testing](https://github.com/rhymeswithmogul/PSPasswordGenerator/assets/47799735/b9a7a3e5-168f-41ef-a9c0-40295e0d6a17)

</details>

**Comment by rhymeswithmogul** [comment]
Wrap your string in single quotes and it should work. That will disable PowerShell's parsing (for everything except another single quote).

Wrapping it in double quotes will work, too, but more characters will be parsed, like the dollar sign. 

This is expected behavior for the PowerShell runtime itself and it's not anything I can fix.

**Comment by rhymeswithmogul** [comment]
However, I just pushed a new commit to that branch which explains this edge case in the contextual help.  Basically, single-quoted strings are not parsed, while double-quoted and bare strings are.

```powershell
PS>  "Hello, $(Write-Output "world!")"
Hello World!

PS>  'Hello, $(Write-Output "world!")'
Hello, $(Write-Output "world!")
```

**Comment by wwc-trevor** [comment]
Not a problem! I am no PS master and do forget about the difference between `'` and `"` when it comes to strings. Thank you for your response and work on this!

**Comment by rhymeswithmogul** [comment]
I think that's me, but thank you for confirming!
